# Generated by Django 4.1.3 on 2022-12-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_name', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('grading_date_time', models.DateField(auto_now=True)),
                ('file_attachement', models.ImageField(upload_to='Assignment')),
                ('final_grade', models.FloatField()),
            ],
        ),
    ]
