# Generated by Django 4.1.3 on 2022-12-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='teachers_notes',
            field=models.CharField(default='reenter', max_length=1000),
        ),
    ]
