# Generated by Django 4.1.3 on 2022-12-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_submission', '0003_student_submitassignment_alter_homework_student_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
